map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
  listen 80;
  server_name app.trackwave.dev;

  root /var/www;           # onde você montou o dist
  index index.html;
  try_files $uri $uri/ /index.html;
}

server {
  listen 80;
  server_name api.trackwave.dev;

  location / {
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade           $http_upgrade;
    proxy_set_header Connection        $connection_upgrade;
    proxy_pass http://trackwave-api-laravel:9051/;
  }
}
