name: Frontend CI

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Copy .env.example to .env"
        run: |
          cp .env.example .env

      - name: "Update .env values"
        run: |
          sed -i "s#VITE_API_URL=.*#VITE_API_URL=${{ secrets.VITE_API_URL }}#" .env

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: "Copiar arquivos para a VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/home/deploy/projects/trackwave-app"
          overwrite: true
          rm: true
      
      - name: "Restarting Docker Container"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/deploy/projects/trackwave-app
            chown -R deploy:deploy ./dist
            cd /home/deploy/projects/trackwave-app/docker/staging
            docker compose up -d --build