name: Frontend CI

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Criar .env"
        run: |
          cp .env.example .env
          sed -i "s#VITE_API_URL=.*#VITE_API_URL=${{ secrets.VITE_API_URL }}#" .env

      - name: "Set up Node.js v20"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: "Install deps & build"
        run: |
          npm ci
          npm run build

      - name: "Stop & clean target with sudo"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ -d /home/deploy/projects/trackwave-app/docker/staging ]; then
              cd /home/deploy/projects/trackwave-app/docker/staging
              docker compose down || true
            fi
            sudo rm -rf /home/deploy/projects/trackwave-app
            sudo mkdir -p /home/deploy/projects/trackwave-app
            sudo chown -R $USER:$USER /home/deploy/projects/trackwave-app

      - name: "Copiar artefatos para a VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/**,nginx/*.conf,nginx/*.template,docker/**,.env"
          target: "/home/deploy/projects/trackwave-app"
          overwrite: true
          debug: true

      - name: "Restarting Docker Container"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/deploy/projects/trackwave-app/docker/staging
            docker compose up -d --build
